First attempt to use v4 api
jon4hz/go-1inch pull request #5
Opened 2021-11-16 12:07 UTC by pcallewaert

2021-11-17 10:21 UTC, jon4hz commented
Hey @pcallewaert, thanks a lot for your contribution. I will take a look at this over the weekend. I've seen that 1inch also added optimism and arbitrum. Could you add those networks to the network mapping?

2021-11-20 10:08 UTC, pcallewaert commented
I've added the 2 networks, and I also renamed ProtocolImages to LiquiditySources to be consistent with the API docs.

2021-11-20 19:01 UTC, jon4hz requested changes
I saw that 1inch also added an endpoint `approve/allowance`. Feel free to add that one as well and otherwise I will.

2021-11-20 19:01 UTC, jon4hz commented on approve.go
>  func (c *Client) ApproveCalldata(ctx context.Context, network, tokenAddress string, opts *ApproveCalldataOpts) (*ApproveCalldataRes, int, error) {
Could you also change the functions and types name so that it is consistent with the URL?

2021-11-22 20:00 UTC, jon4hz approved these changes

2021-11-23 19:29 UTC, pcallewaert commented
Added the `ApproveAllowance`, but had no idea how to test it properly. I tested it with my personal wallet and it works, but don't want to hardcode it 😅

2021-11-25 20:40 UTC, merged